#lang sicp

(define (eval exp env)
  (define (analyze exp)
    (define (self-evaluating? exp)
      (or (number? exp) (string? exp)))
    (define (analyze-self-evaluating exp)
      (lambda (env) exp))
    
    (define (quoted? exp) (tagged-list? exp 'quote))
    (define (text-of-quotation exp) (cadr exp))
    (define (analyze-quoted exp)
      (let ((qval (text-of-quotation exp)))
        (lambda (env) qval)))
    
    (define (variable? exp) (symbol? exp))
    (define (analyze-variable exp)
      (lambda (env) (lookup-variable-value exp env)))
    
    (define (assignment? exp) (tagged-list? exp 'set!))
    (define (assignment-variable exp) (cadr exp))
    (define (assignment-value exp) (caddr exp))
    (define (analyze-assignment exp)
      (let ((var (assignment-variable exp))
            (vproc (analyze (assignment-value exp))))
        (lambda (env)
          (set-variable-value! var (vproc env) env)
          'ok)))
    
    (define (definition? exp) (tagged-list? exp 'define))
    (define (definition-variable exp)
      (let ((interface (cadr exp)))
        (if (symbol? interface)
            interface
            (car interface))))
    (define (definition-value exp)
      (let* ((operands (cdr exp))
             (interface (car operands)))
        (if (symbol? interface)
            (cadr operands)
            (make-lambda (cdr interface)    ; formal parameters
                         (cdr operands))))) ; body
    (define (analyze-definition exp)
      (let ((var (definition-variable exp))
            (vproc (analyze (definition-value exp))))
        (lambda (env)
          (define-variable! var (vproc env) env)
          'ok)))
    
    (define (if? exp) (tagged-list? exp 'if))
    (define (make-if predicate consequent alternative)
      (list 'if predicate consequent alternative))
    (define (if-predicate exp) (cadr exp))
    (define (if-consequent exp) (caddr exp))
    (define (if-alternative exp)
      (let ((alternative (cdddr exp)))
        (if (null? alternative)
            'false
            (car alternative))))
    (define (analyze-if exp)
      (let ((pproc (analyze (if-predicate exp)))
            (cproc (analyze (if-consequent exp)))
            (aproc (analyze (if-alternative exp))))
        (lambda (env)
          (if (true? (pproc env))
              (cproc env)
              (if (eq? 'false aproc)
                  'false
                  (aproc env))))))

    (define (and? exp) (tagged-list? exp 'and))
    (define (or? exp) (tagged-list? exp 'or))
    (define (and->if exp)
      (define result 'true)
      (define (transform exps)
        (if (null? exps)
            result
            (begin (set! result (car exps))
                   (list 'if result (transform (cdr exps))))))
      (transform (cdr exp)))
    (define (or->if exp)
      (define (transform exps)
        (if (null? exps)
            'false
            (let ((value (car exps)))
              (list 'if
                    value
                    value
                    (transform (cdr exps))))))
      (transform (cdr exp)))
    
    (define (lambda? exp) (tagged-list? exp 'lambda))
    (define (make-lambda parameters body)
      (cons 'lambda (cons parameters body)))
    (define (lambda-parameters exp) (cadr exp))
    (define (lambda-body exp) (cddr exp))
    (define (analyze-lambda exp)
      (let ((vars (lambda-parameters exp))
            (bproc (analyze-sequence (lambda-body exp))))
        (lambda (env) (make-procedure vars bproc env))))
    
    (define (begin? exp) (tagged-list? exp 'begin))
    (define (begin-actions exp) (cdr exp))
    (define (last-exp? seq) (null? (cdr seq)))
    (define (first-exp seq) (car seq))
    (define (rest-exps seq) (cdr seq))

    (define (sequence->exp seq)
      (cond ((null? seq) seq)
            ((last-exp? seq) (first-exp seq))
            (else (make-begin seq))))
    (define (make-begin seq) (cons 'begin seq))
    
    (define (analyze-sequence exps)
      (define (execute-sequence procs env)
        (cond ((null? (cdr procs)) ((car procs) env))
              (else ((car procs) env)
                    (execute-sequence (cdr procs) env))))
      (let ((procs (map analyze exps)))
        (if (null? procs)
            (error "Empty sequence -- ANALYZE"))
        (lambda (env) (execute-sequence procs env))))

    (define (cond? exp) (tagged-list? exp 'cond))
    (define (cond-clauses exp) (cdr exp))
    (define (cond-else-clause? clause)
      (eq? (cond-predicate clause) 'else))
    (define (cond-additional-clause? clause)
      (not (null? (cddr clause))))
    (define (cond-predicate clause) (car clause))
    (define (cond-actions clause) (cdr clause))
    (define (cond-test clause) (car clause))
    (define (cond-recipient clause) (caddr clause))
    (define (cond->if exp)
      (define (expand-clauses clauses)
        (if (null? clauses)
            'false                          ; no else clause
            (let ((first (car clauses))
                  (rest (cdr clauses)))
              (if (cond-else-clause? first)
                  (if (null? rest)
                      (sequence->exp (cond-actions first))
                      (error
                       "ELSE clause isn't last -- COND->IF"
                       clauses))
                  (make-if (cond-predicate first)
                           (sequence->exp (cond-actions
                                           first))
                           (expand-clauses rest))))))
      (expand-clauses (cond-clauses exp)))
    
    (define (application? exp) (pair? exp))
    (define (operator exp) (car exp))
    (define (operands exp) (cdr exp))
    (define (no-operands? ops) (null? ops))
    (define (first-operand ops) (car ops))
    (define (rest-operands ops) (cdr ops))
    (define (analyze-application exp)
      (let ((fproc (analyze (operator exp)))
            (aprocs (map analyze (operands exp))))
        (lambda (env)
          (execute-application (fproc env)
                               (map (lambda (aproc)
                                      (aproc env))
                                    aprocs)))))
    (define (execute-application proc args)
      (cond ((primitive-procedure? proc)
             (apply-primitive-procedure proc args))
            ((compound-procedure? proc)
             ((procedure-body proc)
              (extend-environment
               (map make-var-val
                    (procedure-parameters proc)
                    args)
               (procedure-environment proc))))
            (else (error
                   "Unknown procedure type -- EXECUTE-APPLICATION"
                   proc))))
    
    (cond ((self-evaluating? exp) 
           (analyze-self-evaluating exp))
          ((quoted? exp) (analyze-quoted exp))
          ((variable? exp) (analyze-variable exp))
          ((assignment? exp) (analyze-assignment exp))
          ((definition? exp) (analyze-definition exp))
          ((if? exp) (analyze-if exp))
          ((and? exp) (analyze (and->if exp)))
          ((or? exp) (analyze (or->if exp)))
          ((lambda? exp) (analyze-lambda exp))
          ((begin? exp)
           (analyze-sequence (begin-actions exp)))
          ((cond? exp) (analyze (cond->if exp)))
          ((application? exp) (analyze-application exp))
          (else
           (error "Unknown expression type -- ANALYZE"
                  exp))))
  
  ((analyze exp) env))

(define (tagged-list? exp tag)
  (and (pair? exp) (eq? (car exp) tag)))
    
(define (true? x) (not (eq? x false)))
(define (false? x) (eq? x false))
    
(define apply-in-underlying-scheme apply)
(define (primitive-procedure? proc)
  (tagged-list? proc 'primitive))
(define (primitive-implementation proc) (cadr proc))
(define (primitive-procedure-names)
  (frame-variables primitive-procedures))
(define (primitive-procedure-objects)
  (map (lambda (proc)
         (list 'primitive proc))
       (frame-values primitive-procedures)))
(define (apply-primitive-procedure proc args)
  (apply-in-underlying-scheme
   (primitive-implementation proc) args))

(define (make-var-val var val) (cons var val))
(define (variable var-val) (car var-val))
(define (values var-val) (cdr var-val))

(define the-empty-frame '())
(define (make-frame variables-values) variables-values)
(define (frame-variables frame) (map variable frame))
(define (frame-values frame) (map values frame))
(define (add-binding-to-frame! var-val frame)
  (set-cdr! frame (cons (first-var-val frame)
                        (last-var-val frame)))
  (set-car! frame var-val))
(define (first-var-val frame) (car frame))
(define (last-var-val frame) (cdr frame))
(define (lookup-variable-in-frame var frame)
  (if (eq? frame the-empty-frame)
      'Unbound-variable
      (let ((var-val (first-var-val frame)))
        (if (eq? var (variable var-val))
            var-val
            (lookup-variable-in-frame
             var (last-var-val frame))))))

(define the-empty-environment '())
(define (enclosing-environment env) (cdr env))
(define (first-frame env) (car env))
(define (extend-environment frame base-env)
  (cons frame base-env))

(define (lookup-variable var env)
  (if (eq? env the-empty-environment)
      'Unbound-variable
      (let ((var-val (lookup-variable-in-frame
                      var (first-frame env))))
        (if (eq? 'Unbound-variable var-val)
            (lookup-variable
             var (enclosing-environment env))
            var-val))))

(define (lookup-variable-value var env)
  (let ((var-val (lookup-variable var env)))
    (if (eq? 'Unbound-variable var-val)
        (error "Unbound variable" var)
        (values var-val))))

(define (set-variable-value! var val env)
  (let ((var-val (lookup-variable var env)))
    (if (eq? 'Unbound-variable var-val)
        (error "Unbound variable -- SET!" var)
        (set-cdr! var-val val))))

(define (define-variable! var val env)
  (let* ((frame (first-frame env))
         (var-val (lookup-variable-in-frame var frame)))
    (if (eq? 'Unbound-variable var-val)
        (add-binding-to-frame! (make-var-val var val) frame)
        (set-cdr! var-val val))))

(define (make-procedure parameters body env)
  (list 'procedure parameters body env))
(define (compound-procedure? p)
  (tagged-list? p 'procedure))
(define (procedure-parameters p) (cadr p))
(define (procedure-body p) (caddr p))
(define (procedure-environment p) (cadddr p))

(define primitive-procedures
  (make-frame (list (make-var-val 'car car)
                    (make-var-val 'cdr cdr)
                    (make-var-val 'cons cons)
                    (make-var-val 'null? null?)
                    (make-var-val '= =)
                    (make-var-val '< <)
                    (make-var-val '> >)
                    (make-var-val '+ +)
                    (make-var-val '- -)
                    (make-var-val '* *)
                    (make-var-val '/ /)
                    ; (make-var-val ')
                    ; <more primitives>
                    )))

(define (setup-environment)
  (let ((initial-env
         (extend-environment (map make-var-val
                                  (primitive-procedure-names)
                                  (primitive-procedure-objects))
                             the-empty-environment)))
    (define-variable! 'true true initial-env)
    (define-variable! 'false false initial-env)
    initial-env))

(define the-global-environment (setup-environment))

(define (driver-loop)
  (display ";;; M-Eval input:") (newline)
  (let* ((input (read))
         (output (eval input the-global-environment)))
    (display ";;; M-Eval value:") (newline)
    (display output) (newline)
    (newline))
  (driver-loop))

(driver-loop)
